AllCops:
  TargetRubyVersion: 2.4

Style/SymbolArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FileName:
  Exclude:
    - Gemfile
Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true
Style/NumericPredicate:
  AutoCorrect: true
  EnforcedStyle: comparison
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100
Metrics/LineLength:
  Max: 150
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Metrics/BlockNesting:
  Max: 5
